fix: match non-english characters in variables + glossary terms
readmeio/variable pull request #66
Opened 2022-01-27 23:33 UTC by rafegoldberg

## 🧰 What's being changed?
Apparently RegEx's `\w` selector is seriously anglo-centric, and only matches against alphabetic language characters. (You can see the breakage [here](https://my-group.readme.io/kingtest/docs/glossary-testing).) This renders both our variable and glossary components entirely useless in non-english language docs! That is 💩 y. And, as it turns out, quite easy to fix…

- [x] Update our variable pattern to use Unicode `\p{L}` selector.

## 🧬 Testing

We can't directly test this till the change hits ReadMe proper, but you can see the pattern in action [here](https://regexr.com/6e759). Browser support for the RegEx `/u` Unicode flag is [pretty good](https://caniuse.com/mdn-javascript_builtins_regexp_unicode) too!

2022-01-27 23:41 UTC, erunion requested changes
mind adding some unicode tests for this into https://github.com/readmeio/variable/blob/main/__tests__/index.test.jsx#L124-L128

2022-01-27 23:44 UTC, rafegoldberg commented
Yes, thanks for the reminder @erunion! (One day I'll ingrain TDD in to my soul, but that day has yet to come apparently…) Also, gonna make this pattern case-insensitive per @gkoberger's [suggestion](https://readmeio.slack.com/archives/C5B798RFZ/p1643326525583109?thread_ts=1643324628.953939&cid=C5B798RFZ)!

2022-01-28 00:00 UTC, erunion commented on __tests__/index.test.jsx
> +  });
just for good measure

```suggestion
  it('should match non-english characters', () => {
    expect('<<片仮名>>').toMatch(new RegExp(VARIABLE_REGEXP));
  });
  
  it('should match against colons with non-english characters', () => {
    expect('<<glossary:ラベル>>').toMatch(new RegExp(VARIABLE_REGEXP));
  });
```

2022-01-28 00:01 UTC, erunion commented on __tests__/index.test.jsx
> +    expect('<<api.key>>').toMatch(new RegExp(VARIABLE_REGEXP));
```suggestion
    expect('<<api.KeY>>').toMatch(new RegExp(VARIABLE_REGEXP));
```

2022-01-28 00:01 UTC, erunion approved these changes
noted some minor testing improvements but otherwise if all tests are passing 👍

2022-01-28 00:05 UTC, rafegoldberg commented on __tests__/index.test.jsx
> +    expect('<<api.key>>').toMatch(new RegExp(VARIABLE_REGEXP));
lol wtf rafe

2022-01-28 00:05 UTC, kanadgupta approved these changes
![](https://64-media-tumblr-com.cdn.ampproject.org/ii/w820/s/64.media.tumblr.com/8b751d6871e823f689ebc1128c3245b9/d63406015cb0654b-43/s540x810/e2160af35936a3cb0f3e1d9b7982c68fc974617f.gif)

2022-01-28 00:12 UTC, merged